name: Build and Push Docker Server Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/RemoteExec.Server/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Push Server Image
    defaults:
      run:
        working-directory: "./src"
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/remoteexec-server:latest -f ./src/RemoteExec.Server/DockerFile
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/remoteexec-server:latest
